### ISSUE TITLE
Clobbering temporary folder on computer cluster

### ISSUE THREAD

**Issue by RolfSK** [denglab/SeqSero#1]
The temporary directory in which the data is stored is named after the server time. This is a problem when during jobs on a cluster as the directory may be created at the same time by several parallel processes.

One solution could be to use the temporary files module in Python.

Our own quick-fix is to add a random number.
In the script **SeqSero.py:**
**Changed line 8**: `import argparse,os,sys,time` ---> `import argparse,os,sys,time,random`
**added line after line 21**:
```
    request_id = time.strftime("%m_%d_%Y_%H_%M_%S", time.localtime())
    request_id += str(random.randint(1, 10000000))
```

**Comment by ShaokangZhang** [comment]
Hi Rolf,

Good suggestion. In the server version SeqSero, we used the same strategy to avoid replications (by adding random number). But I deleted that part in the linux local version for the aim to make the directory name user-friendly. Sorry about that.

I have updated your codes to the github. Thanks for your suggestions, :)

Regards,
SeqSero Team

**Comment by RolfSK** [comment]
Great! That will save me from having to manually add it every time I pull it ;)

Best,
Rolf
